name: Reusable workflow terraform

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string
        default: 'src'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true


